version: "3.9"
services:
  web:
    build: .

    ports: 
      - 8080:80
    depends_on:
      - mongodb
    restart: on-failure

  mongodb:
    image: mongo:6.0.5
    # environment:
    #   AUTH: yes
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
